#%RAML 1.0 Library
uses:
  ISO: /exchange_modules/cd609ea1-1c8a-4d06-9d4d-230aca5955d4/vfgl-sfcc-iso-standards-data-types/1.0.0/vfgl-sfcc-iso-standards-data-types.raml

types:
  Inventory:
    properties:
      ats:
        type: number

        description: The ats of the product. If it is infinity, the return value is 999999. The value can be overwritten by the OCAPI setting 'product.inventory.ats.max_threshold'.
        example: 0.1
      backorderable:
        type: boolean
        description: A flag indicating whether the product is back orderable.
        example: true
      id:
        type: string
        description: The inventory id.
        example: "aaa"
        required: true
      in_stock_date:
        type: datetime
        description: A flag indicating the date when the product will be in stock.
      orderable:
        type: boolean
        description: A flag indicating whether at least one of products is available to sell.
        example: true
      preorderable:
        type: boolean
        description: A flag indicating whether the product is pre orderable.
        example: true
      stock_level:
        type: number
        description: The stock level of the product. If it is infinity, the return value is 999999. The value can be overwritten by the OCAPI setting 'product.inventory.stock_level.max_threshold'.
        example: 0.1
  SuggestedProduct:
    properties:
      currency:
        type: string
        description: The ISO 4217 mnemonic code of the currency.
        example: "aaa"
      image:
        type: Image
        description: The first image of the product hit for the configured viewtype.
      link:
        type: string
        description: The URL addressing the product.
        example: "aaa"
      price:
        type: number
        description: The sales price of the product. In the case of complex products like a master or a set, this is the minimum price of related child products.
        example: 0.1
      product_id:
        type: string
        description: The id (SKU) of the product.
        example: "aaa"
      product_name:
        type: string
        description: The localized name of the product.
        example: "aaa"
  ProductSearchHit:
    properties:
      currency:
        type: string
        description: The ISO 4217 mnemonic code of the currency.
        example: "aaa"
      hit_type:
        type: string
        description: The type information for the search hit.
        example: "aaa"
      image:
        type: Image
        description: The first image of the product hit for the configured viewtype.
      link:
        type: string
        description: The URL addressing the product.
        example: "aaa"
      orderable:
        type: boolean
        description: A flag indicating whether the product is orderable.
        example: true
      price:
        type: number
        description: The sales price of the product. In case of complex products like master or set this is the minimum price of related child products.
        example: 0.1
      price_max:
        type: number
        description: The maximum sales of related child products in case of complex products like master or set.
        example: 0.1
      price_per_unit:
        type: number
        description: The sales price per unit of the product. In case of complex products like master or set this is the minimum price per unit of related child products.
        example: 0.1
      price_per_unit_max:
        type: number
        description: The maximum sales price per unit of related child products in case of complex products like master or set.
        example: 0.1
      prices:
        type: array
        items:
          type: object
          properties:
            key: string
            value: number
        description: The prices map with price book ids and their values.
      product_id:
        type: string
        description: The id (SKU) of the product.
        example: "aaa"
      product_name:
        type: string
        description: The localized name of the product.
        example: "aaa"
      product_type:
        type: ProductType
        description: The type information for the product.
      represented_product:
        type: ProductRef
        description: The first represented product.
      represented_products:
        type: array
        items:
          type: ProductRef
        description: All the represented products.
      variation_attributes:
        type: array
        items:
          type: VariationAttribute
        description: The array of represented variation attributes (for the master product only). This array can be empty.
  Variant:
    properties:
      link:
        type: string
        description: The URL addressing the product.
        example: "aaa"
        required: true
        minLength: 1
      orderable:
        type: boolean
        description: A flag indicating whether the variant is orderable.
        example: true
      price:
        type: number
        description: The sales price of the variant.
        example: 0.1
      price_per_unit:
        type: number
        description: The sales price of the variant.
        example: 0.1
      product_id:
        type: string
        description: The id (SKU) of the variant.
        example: "aaa"
        required: true
        maxLength: 100
        minLength: 1
      variation_values:
        type: array
        items:
          type: object
          properties:
            key: string
            value: string
        description: The actual variation attribute id - value pairs.
  Master:
    properties:
      link:
        type: string
        description: The URL addressing the master product.
        example: "aaa"
        required: true
        minLength: 1
      master_id:
        type: string
        description: The id (SKU) of the master product.
        example: "aaa"
        required: true
        maxLength: 100
        minLength: 1
      orderable:
        type: boolean
        description: A flag indicating whether at least one of the variants is orderable.
        example: true
      price:
        type: number
        description: The minimum sales price of the related variants.
        example: 0.1
      price_max:
        type: number
        description: The maximum sales of related variants.
        example: 0.1
      price_per_unit:
        type: number
        description: The minimum sales price per unit of the related variants.
        example: 0.1
      price_per_unit_max:
        type: number
        description: The maximum sales price per unit of the related variants.
        example: 0.1
  VariationAttributeValue:
    properties:
      description:
        type: string
        description: The localized description of the variation value.
        example: "aaa"
      image:
        type: Image
        description: The first product image for the configured viewtype and this variation value.
      image_swatch:
        type: Image
        description: The first product image for the configured viewtype and this variation value. (typically the swatch image)
      name:
        type: string
        description: The localized display name of the variation value.
        example: "aaa"
      orderable:
        type: boolean
        description: A flag indicating whether at least one variant with this variation attribute value is available to sell.
        example: true
      value:
        type: string
        description: The actual variation value.
        example: "aaa"
        required: true
        minLength: 1
  ProductSearchRefinementValue:
    properties:
      description:
        type: string
        description: The localized description of the refinement value.
        example: "aaa"
      hit_count:
        type: integer
        description: The number of search hits when selecting the refinement value. Can be 0.
        example: 1
      label:
        type: string
        description: The localized label of the refinement value.
        example: "aaa"
      presentation_id:
        type: string
        description: The optional presentation id associated with the refinement value. The presentation id can be used, for example, to associate an id with an HTML widget.
        example: "aaa"
      value:
        type: string
        description: The refinement value. In the case of an attribute refinement, this is the bucket, the attribute value, or a value range. In the case of a category refinement, this is the category id. In the case of a price refinement,k this is the price range. Ranges are enclosed by parentheses and separated by ".."; for example, "(100..999)" and "(Aa..Fa)" are valid ranges.
        example: "aaa"
      values:
        type: array
        items:
          type: ProductSearchRefinementValue
        description: The array of hierarchical refinement values. This array can be empty.
  ProductType:
    properties:
      bundle:
        type: boolean
        description: A flag indicating whether the product is a bundle.
        example: true
      item:
        type: boolean
        description: A flag indicating whether the product is a standard item.
        example: true
      master:
        type: boolean
        description: A flag indicating whether the product is a master.
        example: true
      option:
        type: boolean
        description: A flag indicating whether the product is an option.
        example: true
      set:
        type: boolean
        description: A flag indicating whether the product is a set.
        example: true
      variant:
        type: boolean
        description: A flag indicating whether the product is a variant.
        example: true
      variation_group:
        type: boolean
        description: A flag indicating whether the product is a variation group.
        example: true
  OptionValue:
    properties:
      default:
        type: boolean
        description: A flag indicating whether this option value is the default one.
        example: true
      id:
        type: string
        description: The id of the option value.
        example: "aaa"
        required: true
        maxLength: 100
        minLength: 1
      name:
        type: string
        description: The localized name of the option value.
        example: "aaa"
      price:
        type: number
        description: The effective price of this option value.
        example: 0.1
  Recommendation:
    properties:
      callout_msg:
        type: string
        description: The localized callout message of the recommendation.
        example: "aaa"
      image:
        type: Image
        description: The image of the recommendation.
      long_description:
        type: string
        description: The localized long description of the recommendation.
        example: "aaa"
      name:
        type: string
        description: The localized name of the recommendation.
        example: "aaa"
      recommendation_type:
        type: RecommendationType
        description: The recommendation type of the recommendation.
      recommended_item_id:
        type: string
        description: The recommended item id of the recommendation.
        example: "aaa"
      recommended_item_link:
        type: string
        description: The recommended item link of the recommendation.
        example: "aaa"
      short_description:
        type: string
        description: The localized short description of the recommendation.
        example: "aaa"
  SuggestedCategory:
    properties:
      id:
        type: string
        description: The id of the category.
        example: "aaa"
      link:
        type: string
        description: The URL addressing the category.
        example: "aaa"
      name:
        type: string
        description: The localized name of the category.
        example: "aaa"
      parent_category_name:
        type: string
        description: The name of the parent category.
        example: "aaa"
  ProductRef:
    properties:
      id:
        type: string
        description: The ID of the product reference.
        example: "aaa"
        required: true
      link:
        type: string
        description: The link to the product reference.
        example: "aaa"
        required: true
        maxLength: 100
  Product:
    properties:
      brand:
        type: string
        description: The product's brand.
        example: "aaa"
      bundled_products:
        type: array
        items:
          type: BundledProduct
        description: The array of all bundled products of this product.
      currency:
        type: string
        description: The ISO 4217 mnemonic code of the currency.
        example: "aaa"
      ean:
        type: string
        description: The European Article Number.
        example: "aaa"
      id:
        type: string
        description: The id (SKU) of the product.
        example: "aaa"
        required: true
        maxLength: 100
        minLength: 1
      image_groups:
        type: array
        items:
          type: ImageGroup
        description: The array of product image groups.
      inventories:
        type: array
        items:
          type: Inventory
        description: The array of product inventories explicitly requested via 'inventory_ids' query parameter. This property is only returned in context of the 'availability' expansion.
      inventory:
        type: Inventory
        description: The site default inventory information. This property is only returned in context of the 'availability' expansion.
      long_description:
        type: string
        description: The localized product long description.
        example: "aaa"
      manufacturer_name:
        type: string
        description: The products manufacturer name.
        example: "aaa"
      manufacturer_sku:
        type: string
        description: The products manufacturer sku.
        example: "aaa"
      master:
        type: Master
        description: The master product information. Only for types master, variation group and variant.
      min_order_quantity:
        type: number
        description: The minimum order quantity for this product.
        example: 0.1
      name:
        type: string
        description: The localized product name.
        example: "aaa"
      options:
        type: array
        items:
          type: Option
        description: The array of product options. This array can be empty. Only for type option.
      page_description:
        type: string
        description: The localized products page description.
        example: "aaa"
      page_keywords:
        type: string
        description: The localized products page description.
        example: "aaa"
      page_title:
        type: string
        description: The localized products page title.
        example: "aaa"
      price:
        type: number
        description: The sales price of the product. In case of complex products like master or set this is the minimum price of related child products.
        example: 0.1
      price_max:
        type: number
        description: The maximum sales of related child products in case of complex products like master or set.
        example: 0.1
      price_per_unit:
        type: number
        description: The sales price per unit of the product. In case of complex products like master or set this is the minimum price per unit of related child products.
        example: 0.1
      price_per_unit_max:
        type: number
        description: The maximum sales price per unit of related child products in case of complex products like master or set.
        example: 0.1
      prices:
        type: array
        items:
          type: object
          properties:
            key: string
            value: number
        description: The prices map with price book ids and their values.
      primary_category_id:
        type: string
        description: The id of the products primary category.
        example: "aaa"
      product_links:
        type: array
        items:
          type: ProductLink
        description: The array of source and target products links information.
      product_promotions:
        type: array
        items:
          type: ProductPromotion
        description: The array of active customer product promotions for this product. This array can be empty. Coupon promotions are not returned in this array.
      recommendations:
        type: array
        items:
          type: Recommendation
        description: Returns a list of recommendations.
      set_products:
        type: array
        items:
          type: Product
        description: The array of set products of this product.
      short_description:
        type: string
        description: The localized product short description.
        example: "aaa"
      step_quantity:
        type: number
        description: The steps in which the order amount of the product can be increased.
        example: 0.1
      type:
        type: ProductType
        description: The product type information. Can be one or multiple of the following values- item,master,variation_group,variant,bundle,set.
      unit:
        type: string
        description: The sales unit of the product.
        example: "aaa"
      unit_measure:
        type: string
        description: The unitMeasure of the product.
        example: "aaa"
      unit_quantity:
        type: number
        description: 
        example: 0.1
      upc:
        type: string
        description: The Universal Product Code.
        example: "aaa"
      valid_from:
        type: datetime
        description: The time when product is valid from.
        example: 9999-12-31T00:00:00.0Z
      valid_to:
        type: datetime
        description: The time when product is valid to.
        example: 9999-12-31T00:00:00.0Z
      variants:
        type: array
        items:
          type: Variant
        description: The array of actual variants. This array can be empty. Only for types master, variation group and variant.
      variation_attributes:
        type: array
        items:
          type: VariationAttribute
        description: Sorted array of variation attributes information. This array can be empty. Only for types master, variation group and variant.
      variation_groups:
        type: array
        items:
          type: VariationGroup
        description: The array of actual variation groups. This array can be empty. Only for types master, variation group and variant.
      variation_values:
        type: array
        items:
          type: object
          properties:
            key: string
            value: string
        description: The actual variation attribute id - value pairs. Only for type variant and variation group.
  ImageGroup:
    properties:
      images:
        type: array
        items:
          type: Image
        description: The images of the image group.
      variation_attributes:
        type: array
        items:
          type: VariationAttribute
        description: Returns a list of variation attributes applying to this image group.
      view_type:
        type: string
        description: The image view type.
        example: "aaa"
  ProductSearchSortingOption:
    properties:
      id:
        type: string
        description: The id of the sorting option.
        example: "aaa"
      label:
        type: string
        description: The localized label of the sorting option.
        example: "aaa"
  ProductSearchResult:
    properties:
      count:
        type: integer
        description: The number of returned documents.
        example: 1
      hits:
        type: array
        items:
          type: ProductSearchHit
        description: The sorted array of search hits. This array can be empty.
      next:
        type: string
        description: The URL of the next result page.
        example: "aaa"
      previous:
        type: string
        description: The URL of the previous result page.
        example: "aaa"
      query:
        type: string
        description: The query String that was searched for.
        example: "aaa"
      refinements:
        type: array
        items:
          type: ProductSearchRefinement
        description: The sorted array of search refinements. This array can be empty.
      search_phrase_suggestions:
        type: Suggestion
        description: The suggestion given by the system for the submitted search phrase.
      select:
        type: string
        description: The fields that you want to select.
        example: "aaa"
      selected_refinements:
        type: array
        items:
          type: object
          properties:
            key: string
            value: string
        description: A map of selected refinement attribute id/value(s) pairs. The sorting order is the same as in request URL.
      selected_sorting_option:
        type: string
        description: The id of the applied sorting option.
        example: "aaa"
      sorting_options:
        type: array
        items:
          type: ProductSearchSortingOption
        description: The sorted array of search sorting options. This array can be empty.
      start:
        type: integer
        description: The zero-based index of the first search hit to include in the result.
        example: 1
      total:
        type: integer
        description: The total number of documents.
        example: 1
  BundledProduct:
    properties:
      product:
        type: Product
        description: The product being bundled.
      quantity:
        type: number
        description: For the product being bundled, the quantity added to the bundle.
        example: 0.1
  SuggestedContent:
    properties:
      id:
        type: string
        description: The id of the content.
        example: "aaa"
      link:
        type: string
        description: The URL addressing the content.
        example: "aaa"
      name:
        type: string
        description: The localized name of the content.
        example: "aaa"
  SuggestedTerm:
    properties:
      completed:
        type: boolean
        description: Returns whether this term value is a completion match.
      corrected:
        type: boolean
        description: Returns whether this term value is a correction match.
      exact_match:
        type: boolean
        description: Returns whether this term value is a exact match.
      value:
        type: string
        description: Returns the term value.
        example: "aaa"
  SuggestedPhrase:
    properties:
      exact_match:
        type: boolean
        description: Returns whether this suggested phrase exactly matches the user input search phrase.
      phrase:
        type: string
        description: Returns the suggested search phrase.
        example: "aaa"
  SuggestedTerms:
    properties:
      original_term:
        type: string
        description: Returns the original term that the suggested terms relates to.
        example: "aaa"
      terms:
        type: array
        items:
          type: SuggestedTerm
        description: Returns the suggested terms.
  ProductSearchRefinement:
    properties:
      attribute_id:
        type: string
        description: The id of the search refinement attribute. In the case of an attribute refinement, this is the attribute id. Custom attributes are marked by the prefix "c_" (for example, "c_refinementColor"). In the case of a category refinement, the id must be "cgid". In the case of a price refinement, the id must be "price".
        example: "aaa"
        required: true
      label:
        type: string
        description: The localized label of the refinement.
        example: "aaa"
      values:
        type: array
        items:
          type: ProductSearchRefinementValue
        description: The sorted array of refinement values. This array can be empty.
  ProductPromotion:
    properties:
      callout_msg:
        type: string
        description: The localized call-out message of the promotion.
        example: "aaa"
      link:
        type: string
        description: The URL addressing the promotion.
        example: "aaa"
      promotion_id:
        type: string
        description: The unique id of the promotion.
        example: "aaa"
      promotional_price:
        type: number
        description: The promotional price for this product.
        example: 0.1
  ProductLink:
    properties:
      source_product_id:
        type: string
        description: The semantic id of the product from which this product link is coming.
        example: "aaa"
      source_product_link:
        type: string
        description: The URL addressing the product from which this product link is coming.
        example: "aaa"
      target_product_id:
        type: string
        description: The semantic id of the product to which this product link is pointing.
        example: "aaa"
      target_product_link:
        type: string
        description: The URL addressing the product to which this product link is pointing.
        example: "aaa"
      type:
        type: string
        enum:
          - "cross_sell"
          - "replacement"
          - "up_sell"
          - "accessory"
          - "newer_version"
          - "alt_orderunit"
          - "spare_part"
          - "other"
        description: The type of this product link.
        example: cross_sell
  VariationGroup:
    properties:
      link:
        type: string
        description: The URL addressing the product.
        example: "aaa"
      orderable:
        type: boolean
        description: A flag indicating whether the variation group is orderable.
        example: true
      price:
        type: number
        description: The sales price of the variation group.
        example: 0.1
      price_per_unit:
        type: number
        description: The sales price per unit of the variation group.
        example: 0.1
      product_id:
        type: string
        description: The id (SKU) of the variation group.
        example: "aaa"
        maxLength: 100
        minLength: 1
      variation_values:
        type: array
        items:
          type: object
          properties:
            key: string
            value: string
        description: The actual variation attribute id - value pairs.
  VariantGroup:
    properties:
      link:
        type: string
        description: The URL addressing the product.
        example: "aaa"
      orderable:
        type: boolean
        description: A flag indicating whether the variation group is orderable.
        example: true
      price:
        type: number
        description: The sales price of the variation group.
        example: 0.1
      price_per_unit:
        type: number
        description: The sales price per unit of the variation group.
        example: 0.1
      product_id:
        type: string
        description: The id (SKU) of the variation group.
        example: "aaa"
        maxLength: 100
        minLength: 1
      variation_values:
        type: array
        items:
          type: object
          properties:
            key: string
            value: string
        description: The actual variation attribute id - value pairs.
  Image:
    properties:
      alt:
        type: string
        description: The localized alternative text of the image.
        example: "aaa"
      dis_base_link:
        type: string
        description: Base URL for dynamic image service address. This is only shown, if the image is stored on the server and DIS is enabled.
        example: "aaa"
      link:
        type: string
        description: The URL of the actual image.
        example: "aaa"
        required: true
        minLength: 1
      title:
        type: string
        description: The localized title of the image.
        example: "aaa"
  Suggestion:
    properties:
      brands:
        type: array
        items:
          type: string
        description: The sorted list of suggested brands. This list can be empty.
      categories:
        type: array
        items:
          type: SuggestedCategory
        description: The sorted list of suggested categories. This list can be empty.
      content:
        type: array
        items:
          type: SuggestedContent
        description: The sorted list of suggested content. This list can be empty.
      custom_suggestions:
        type: array
        items:
          type: string
        description: The sorted list of suggested custom suggestions. This list can be empty.
      products:
        type: array
        items:
          type: SuggestedProduct
        description: The sorted list of suggested products. This list can be empty.
      suggested_phrases:
        type: array
        items:
          type: SuggestedPhrase
        description: A list of suggested phrases. This list can be empty.
      suggested_terms:
        type: array
        items:
          type: SuggestedTerms
        description: A list of suggested terms. This list can be empty.
  RecommendationType:
    properties:
      display_value:
        type: string
        description: The localized display value of the recommendation type.
        example: "aaa"
      value:
        type: integer
        description: The value of the recommendation type.
        example: 1
  Option:
    properties:
      description:
        type: string
        description: The localized description of the option.
        example: "aaa"
      id:
        type: string
        description: The id of the option.
        example: "aaa"
        required: true
        maxLength: 100
        minLength: 1
      image:
        type: string
        description: The URL to the option image.
        example: "aaa"
      name:
        type: string
        description: The localized name of the option.
        example: "aaa"
      values:
        type: array
        items:
          type: OptionValue
        description: The array of option values. This array can be empty.
  VariationAttribute:
    properties:
      id:
        type: string
        description: The id of the variation attribute.
        example: "aaa"
        required: true
        minLength: 1
      name:
        type: string
        description: The localized display name of the variation attribute.
        example: "aaa"
      values:
        type: array
        items:
          type: VariationAttributeValue
        description: The sorted array of variation values. This array can be empty.
  Category:
    properties:
      categories:
        type: array
        items:
          type: Category
        description: Array of subcategories. Can be empty.
      description:
        type: string
        description: The localized description of the category.
        example: "aaa"
      id:
        type: string
        description: The id of the category.
        example: "aaa"
      image:
        type: string
        description: The URL to the category image.
        example: "aaa"
      name:
        type: string
        description: The localized name of the category.
        example: "aaa"
      page_description:
        type: string
        description: The localized page description of the category.
        example: "aaa"
      page_keywords:
        type: string
        description: The localized page keywords of the category.
        example: "aaa"
      page_title:
        type: string
        description: The localized page title of the category.
        example: "aaa"
      parent_category_id:
        type: string
        description: The id of the parent category.
        example: "aaa"
      parent_category_tree:
        type: array
        items:
          type: PathRecord
        description: List of parent categories
      thumbnail:
        type: string
        description: The URL to the category thumbnail.
        example: "aaa"
  PathRecord:
    properties:
      id:
        type: string
        description: The id of the category path.
        example: "aaa"
      name:
        type: string
        description: The name of the category path.
        example: "aaa"
  ProductResult:
    properties:
      count:
        type: integer
      data:
        type: array
        items:
          type: Product
      total:
        type: integer
        description: The total number of documents.
        example: 2
  
  SubscribeRequest:
    properties:
      email_address: string
      sku: string
  SubscribeResponse:
    properties:
    count: number
      action: string
      queryString: string
      locale: string
      status: string
      message: string